# Generated by Django 3.2.10 on 2022-01-04 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Name of the Agent', max_length=50, verbose_name='Full Name')),
                ('picture', models.ImageField(blank=True, help_text='Upload an image of the agent', null=True, upload_to='agents/photos/', verbose_name="Agent's Photo")),
                ('email', models.EmailField(max_length=300, verbose_name='Email of Agent')),
                ('phone', models.PositiveSmallIntegerField(help_text='Phone number of this agent', verbose_name='Phone of Agent')),
                ('date_joined', models.DateField(help_text='What date this this Agent join the agency?')),
                ('verified', models.BooleanField(default=False, help_text='Is this agent verified? Tick if yes.')),
            ],
            options={
                'ordering': ('date_joined',),
            },
        ),
    ]
