# Generated by Django 3.2.10 on 2022-01-04 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='phone',
            field=models.PositiveIntegerField(help_text='Phone number of this agent', verbose_name='Phone of Agent'),
        ),
    ]
