# Generated by Django 3.2.10 on 2022-01-07 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0004_apartment_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='featured',
            field=models.BooleanField(default=False, help_text='If this apartment is featured, it is going to be displayed on the homepage and also will be at the top of apartment listings', verbose_name='Featured Listing'),
        ),
    ]
