# Generated by Django 3.2.10 on 2022-01-10 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0006_alter_apartment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='agent_fee',
            field=models.FloatField(blank=True, help_text='Amount to pay to the agent.', null=True, verbose_name="Agent's Fee ( amount )"),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='monthly_rent_payment',
            field=models.FloatField(help_text='How much is a tenant going to pay for the place every month?', verbose_name='Monthly Rent Payment'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='total_rent_payment',
            field=models.FloatField(help_text='Amount tenant will pay over years of residency, monthly_payment * advance_years', verbose_name='Total Rent Payment'),
        ),
    ]
