# Generated by Django 3.2.11 on 2022-01-17 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0009_auto_20220117_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='location',
            field=models.CharField(default='', help_text='Where is this apartment located?', max_length=50, verbose_name='Location'),
        ),
    ]
