# Generated by Django 3.2.11 on 2022-01-21 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0010_alter_apartment_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='advance_years',
            field=models.PositiveSmallIntegerField(choices=[(1, '1+'), (2, '2+'), (3, '3+'), (4, '4+'), (5, '5+'), (6, '6+'), (7, '7+'), (8, '8+'), (9, '9+'), (10, '10+')], default=1, help_text='If this place is being rented out, how many years of advance payment is required?', verbose_name='Years of Advance Payment'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='baths',
            field=models.PositiveSmallIntegerField(choices=[(1, '1+'), (2, '2+'), (3, '3+'), (4, '4+'), (5, '5+'), (6, '6+'), (7, '7+'), (8, '8+'), (9, '9+'), (10, '10+')], default=1, help_text='How many baths are in this apartment?', verbose_name='Number of Baths'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='bedrooms',
            field=models.PositiveSmallIntegerField(choices=[(1, '1+'), (2, '2+'), (3, '3+'), (4, '4+'), (5, '5+'), (6, '6+'), (7, '7+'), (8, '8+'), (9, '9+'), (10, '10+')], default=1, help_text='What is the total number of bedrooms in this apartment?', verbose_name='Number of Bedrooms'),
        ),
    ]
