# Generated by Django 3.2.11 on 2022-01-23 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0013_alter_apartment_major_city'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='apartment',
            index=models.Index(fields=['-upload_time'], name='ordering_idx'),
        ),
        migrations.AddIndex(
            model_name='apartment',
            index=models.Index(fields=['featured', 'verified', 'major_city', 'location', 'bedrooms', 'baths', 'advance_years', 'monthly_rent_payment'], name='filter_idx'),
        ),
    ]
