# Generated by Django 3.2.10 on 2022-01-06 15:10

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featured_image', models.ImageField(upload_to='featured_images/about/', verbose_name='Featured Image')),
                ('about_company', models.TextField(help_text='Enter text to tell visitors what this company is about, a little background story', verbose_name='About Company')),
            ],
        ),
        migrations.CreateModel(
            name='ServicesSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featured_image', models.ImageField(upload_to='featured_images/services/', verbose_name='Featured Image')),
                ('description', models.TextField(help_text='Enter text to tell visitors what this company is about, a little background story', verbose_name='Brief Description of Services')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name of the service', max_length=100, verbose_name='Name of Service')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name')),
                ('service_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='pages.servicessection', verbose_name='Service Section')),
            ],
        ),
    ]
