# Generated by Django 3.2.10 on 2022-01-12 19:09

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='Enter the name of this page, e.g HomePage', max_length=20, verbose_name='Name of Page')),
                ('banner_image', models.ImageField(help_text='Choose an image that will be featured on the banner of the homepage', upload_to='featured_images/homepage/', verbose_name='Banner Image')),
                ('banner_heading_text', models.CharField(default='Discover Your Perfect Home', help_text='Enter the text that will be displayed boldly on the banner on the homepage', max_length=100, verbose_name='Banner Heading Text')),
                ('banner_sub_heading_text', models.CharField(default='Search nearby for apartments, and homes for rent.', help_text='Enter the text that will be displayed below the bold text on the banner', max_length=130, verbose_name='Banner Sub Heading Text')),
            ],
        ),
        migrations.CreateModel(
            name='ServicesSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=10, verbose_name='Name of Section')),
                ('featured_image', models.ImageField(upload_to='featured_images/services/', verbose_name='Featured Image')),
                ('description', models.TextField(help_text='Enter text to tell visitors what this company is about, a little background story', verbose_name='Brief Description of Services')),
                ('page', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='services_section', to='pages.homepage')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name of the service', max_length=100, verbose_name='Name of Service')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name')),
                ('service_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='pages.servicessection', verbose_name='Service Section')),
            ],
        ),
        migrations.CreateModel(
            name='FrequentlyAskedQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(help_text='Enter the question', max_length=300, verbose_name='Question')),
                ('answer', models.TextField(help_text='Enter the answer to this question', verbose_name='Answer')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frequently_asked_questions', to='pages.homepage')),
            ],
        ),
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=10, verbose_name='Name of Section')),
                ('featured_image', models.ImageField(upload_to='featured_images/about/', verbose_name='Featured Image')),
                ('heading', models.CharField(default='', help_text='Heading to display on the about section, this can be the name of the company. e.g Isotach Global', max_length=200, verbose_name='Heading of About')),
                ('about_company', models.TextField(help_text='Enter text to tell visitors what this company is about, a little background story', verbose_name='About Company')),
                ('page', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='about_section', to='pages.homepage')),
            ],
        ),
    ]
