# Generated by Django 3.2.10 on 2022-01-06 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutsection',
            name='heading',
            field=models.CharField(default='', help_text='Heading to display on the about section, this can be the name of the company. e.g Isotach Global', max_length=200, verbose_name='Heading of About'),
        ),
    ]
