# Generated by Django 3.2.11 on 2022-01-22 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_remove_homepage_banner_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='banner_image',
            field=models.ImageField(help_text='Choose an image that will be featured on the banner of the homepage', null=True, upload_to='featured_images/homepage/', verbose_name='Banner Image'),
        ),
    ]
