# Generated by Django 3.2.11 on 2022-01-28 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_homepage_banner_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='service_section',
        ),
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.TextField(default='', help_text='Enter a brief description for this service', max_length=500, verbose_name='Brief Description of Service'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='page',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='services', to='pages.homepage'),
        ),
        migrations.DeleteModel(
            name='ServicesSection',
        ),
    ]
