# Generated by Django 3.2.10 on 2022-01-07 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='name',
            field=models.CharField(default='', help_text='Enter the name of this page, e.g HomePage', max_length=20, verbose_name='Name of Page'),
        ),
    ]
