# Generated by Django 3.2.10 on 2022-01-07 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_servicessection_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrequentlyAskedQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(help_text='Enter the question', max_length=300, verbose_name='Question')),
                ('answer', models.TextField(help_text='Enter the answer to this question', verbose_name='Answer')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frequently_asked_questions', to='pages.homepage')),
            ],
        ),
    ]
