# Generated by Django 3.2.11 on 2022-02-01 02:41

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Enter your full name', max_length=50, verbose_name='Full Name')),
                ('city', models.CharField(help_text='Enter your city or town', max_length=100, verbose_name='City / Town')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('email', models.EmailField(help_text='Enter your email address', max_length=300, verbose_name='Email Address')),
                ('message', models.TextField(help_text='Enter your message', max_length=1000, verbose_name='Message')),
            ],
        ),
    ]
