# Generated by Django 3.2.11 on 2022-02-01 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_rename_contactform_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Enter your full name', max_length=50, verbose_name='Full Name')),
                ('email', models.EmailField(help_text='Enter your email address', max_length=300, verbose_name='Email Address')),
            ],
            options={
                'verbose_name': 'Newsletter Signup',
                'verbose_name_plural': 'Newsletter Signups',
            },
        ),
    ]
