# Generated by Django 3.2.11 on 2022-02-01 19:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_newsletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='signup_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
