# Generated by Django 3.2.11 on 2022-02-02 19:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_inquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='date_submitted',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
