# Generated by Django 3.2.11 on 2022-02-03 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0010_auto_20220203_1145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inquiry',
            name='apartment',
        ),
        migrations.AddField(
            model_name='inquiry',
            name='apartment_link',
            field=models.URLField(default='', verbose_name='Link to Apartment'),
        ),
    ]
