# Generated by Django 3.2.11 on 2022-02-03 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0011_auto_20220203_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='agent_name',
            field=models.CharField(default='', max_length=50, verbose_name="Agent's Name"),
        ),
    ]
