# Generated by Django 3.2.11 on 2022-02-03 21:17

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0012_alter_inquiry_agent_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50, verbose_name='Full Name')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('email', models.EmailField(max_length=300, verbose_name='Email Address')),
                ('submitted', models.DateTimeField(auto_now_add=True)),
                ('apartment_link', models.URLField(default='', verbose_name='Link to Apartment')),
                ('apartment_title', models.CharField(default='', max_length=200, verbose_name='Apartment Title')),
                ('agent_name', models.CharField(default='', max_length=50, verbose_name="Agent's Name")),
                ('meeting_date_and_time', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Scheduled Meeting',
                'verbose_name_plural': 'Scheduled Meetings',
                'ordering': ('-submitted',),
            },
        ),
        migrations.RenameField(
            model_name='inquiry',
            old_name='date_submitted',
            new_name='submitted',
        ),
    ]
