# Generated by Django 3.2.11 on 2022-02-03 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0013_auto_20220203_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='submitted',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Form Submission Date and Time'),
        ),
        migrations.AlterField(
            model_name='schedulemeeting',
            name='submitted',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Form Submission Date and Time'),
        ),
    ]
