# Generated by Django 3.2.11 on 2022-02-08 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0015_siteadmin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SiteAdmin',
            new_name='SiteAdministrator',
        ),
    ]
